Application has thrown an uncaught exception and is terminated:
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (C:\Work\Jokes.com\JokesAPI\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (C:\Work\Jokes.com\JokesAPI\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (C:\Work\Jokes.com\JokesAPI\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
